### Register a new user
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Елизавета",
  "email": "lizabeth.kilback3@hotmail.com",
  "password": "123456"
}


### Login a user
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "lizabeth.kilback3@hotmail.com",
  "password": "123456"
}

### Check auth
GET http://localhost:4000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpemFiZXRoLmtpbGJhY2szQGhvdG1haWwuY29tIiwibmFtZSI6ItCV0LvQuNC30LDQstC10YLQsCIsImlhdCI6MTcyNTc5MjM1NCwiZXhwIjoxNzI1Nzk1OTU0fQ.iwaJ4k9sSg52fdnsTpVoSc3-wajQMyAB7805cN4z_kI
