services:
  guitar-shop-2024.api.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: guitar-shop-2024.api.rabbitmq
    hostname: rabbitmq
    ports:
      - '15682:15672'
      - '5682:5672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  guitar-shop-2024.mongodb:
    image: mongo
    restart: always
    container_name: guitar-shop-2024.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"
    volumes:
      - guitar-shop-2024.mongodb:/data/db

  guitar-shop-2024.postgres:
    image: postgres:14-alpine
    container_name: guitar-shop-2024.postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "guitar-shop-2024.shop"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - guitar-shop-2024.postgres:/var/lib/postgresql/data

volumes:
    guitar-shop-2024.mongodb:
    guitar-shop-2024.postgres:
